### ISSUE TITLE
Add support for shipping zones

### ISSUE THREAD

**Issue by JarrydLong** [Collivery/Collivery-WooCommerce#15]
Adding support for shipping zones in the latest versions of Woocommerce (2.6.4)

![image](https://cloud.githubusercontent.com/assets/8989542/18597874/52478b30-7c50-11e6-892a-5e16cada25f3.png)

**Comment by brycelarge** [comment]
Hi Jarryd, I dont see this as an issue more of a feature request as the plugin does still work. Would be great if you could contribute in anyway in building such a feature?

**Comment by JarrydLong** [comment]
Hi Bryce

Unfortunately (from what I've seen), WooCommerce released Shipping Zones in Version 2.6 which replaced Shipping Methods. 

When using this plugin, although it can be activated, there's no way to 'Enable' it to any of your shipping parameters at the moment as this would need to be an option under the above Shipping method dropdown. In essence, it doesn't show up anywhere on the site for the user to select between 'Flat Rate' or 'MDS' for example. 

I'd be more than willing to contribute in building this in during the course of this week though :)

**Comment by Xethron** [comment]
Hello @JarrydLong!

Thank you for raising this issue and your willingness to help. Let us know if you need anything and we'll help where we can :)

**Comment by brycelarge** [comment]
Closing this issue, Shipping Zones will be supported in our next release
