### ISSUE TITLE
Unfortunately we do not ship to . Please enter an alternative shipping address. Invalid shipping method

### ISSUE THREAD

**Issue by sidn041** [Collivery/Collivery-WooCommerce#3]
Hi, 
getting this issue on my site dealsza.co.za
"Unfortunately we do not ship to . Please enter an alternative shipping address.
Invalid shipping method"
I have same settings as mentioned in your instruction.
please advise.
thanks
Sid

**Comment by brycelarge** [comment]
Hi Sid, I think that message is coming from Woocommerce not the plugin, possibly have to do with your settings as to where you are able to ship to.
