### ISSUE TITLE
v2.2.7 or 2.2.8?

### ISSUE THREAD

**Issue by BernardMyburgh** [Collivery/Collivery-WooCommerce#6]
In collivery.php MDS Version is 2.2.7, yet Wordpress tells me update 2.2.8 is available. Clicking "Update Now" also does not actually update the plugin.

**Comment by brycelarge** [comment]
We have not figured that one out yet, however you can right click on Update Now and click on open in new tab, then the update works as normal. Your also welcome to contribute, if you find a fix for this.
