### ISSUE TITLE
Uncaught ReferenceError: add_location_type_to_session is not defined

### ISSUE THREAD

**Issue by BernardMyburgh** [Collivery/Collivery-WooCommerce#7]
No matter the installation, fresh or on old site, I always get this error in the console log
`Uncaught ReferenceError: add_location_type_to_session is not defined`

Am I missing a step in the setup? It seems to work fine sometimes, but then other times it doesn't, i.e. I get a "Shipping costs will be calculated once you have provided your address." even if I have entered my address. Not sure if this issue is linked with the Uncaught ReferenceError above.

**Comment by brycelarge** [comment]
Hi Bernard, That should have been removed 2 or 3 versions ago, not sure what happened. I have released another version which fixes that. Also just as a note, if you create issues here I cant promise how long it would take to respond or fix, if you email integration@collivery.co.za you will have access to 5 developers all with the ability to assist you.

**Comment by Xethron** [comment]
Hello @BernardMyburgh, has this issue been resolved? Can it be closed?
